### PR TITLE
Prettied up some lines in events.js.

### PR DESCRIPTION
**Pull request by mattrafuse**
Hey, just getting the hang of git, learning some more stuff.

I mostly just prettied up some variable declarations.

### CODE REVIEW

**Comment by Frozenfire92** [comment]
Looks good to me. Although not standard js style to have curlys on their own line this is ok

**Comment by mattrafuse** [comment]
Ok, I'll change it back then. Might as well follow style guidlines.

**Comment by Glavin001** [comment]
> Although not standard js style to have curlys on their own line this is ok

Someone must've taken Scobey's course :stuck_out_tongue_winking_eye: 

> Might as well follow style guidlines.

We should add linting to this project and let Travis CI validate the code from Pull Requests.

**Comment by mattrafuse** [comment]
Guilty as charged. Lose points otherwise? Come on..

**Pull request merged**
